---
apiVersion: v1
kind: Service
metadata:
  name: tokenizer
  namespace: wb-pipe
  labels:
    app: tokenizer
    product: engine
spec:
  ports:
  - name: http-admin
    port: 8075
    targetPort: 8075
    protocol: TCP
  selector:
    app: tokenizer
    product: engine
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tokenizer
  namespace: wb-pipe
  labels:
    app: tokenizer
    product: engine
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/port: "8075"
        prometheus.io/scrape: "true"
      labels:
        app: tokenizer
        product: engine
    spec:
      containers:
      - name: service
        image: eu.gcr.io/adarga-docker/tokenizer:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http-admin
          containerPort: 8075
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: http-admin
          initialDelaySeconds: 200
          periodSeconds: 10
        resources:
          requests:
            cpu: 250m
            memory: 5Gi
